@startuml
component messagecomponents {
component messagecomponents.injector {
component messagecomponents.injector.email {
}
component messagecomponents.injector.sms {
}
}
component messagecomponents.consumer {
}
component messagecomponents.test {
}
component messagecomponents.service {
component messagecomponents.service.email {
}
component messagecomponents.service.sms {
}
}
}
messagecomponents.injector.email -() MessageServiceInjector
messagecomponents.consumer -() MessageConsumer
messagecomponents.service.email -() MessageService
messagecomponents.service.sms -() MessageService
messagecomponents.injector.sms -() MessageServiceInjector
messagecomponents.injector.email -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector.email -(0- messagecomponents.service : "MessageService"
messagecomponents.consumer -(0- messagecomponents.service : "MessageService"
messagecomponents.injector -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector.sms -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector.sms -(0- messagecomponents.service : "MessageService"
messagecomponents.test -(0- messagecomponents.consumer : "MessageConsumer"
@enduml
