@startuml
package messagecomponents {
package messagecomponents.injector {
package messagecomponents.injector.email {
}
package messagecomponents.injector.sms {
}
}
package messagecomponents.consumer {
}
package messagecomponents.test {
}
package messagecomponents.service {
package messagecomponents.service.email {
}
package messagecomponents.service.sms {
}
}
}
messagecomponents.service.email -() MessageService
messagecomponents.injector.sms -() MessageServiceInjector
messagecomponents.service.sms -() MessageService
messagecomponents.injector.email -() MessageServiceInjector
messagecomponents.consumer -() MessageConsumer
messagecomponents.injector.sms -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector.sms -(0- messagecomponents.service : "MessageService"
messagecomponents.test -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector.email -(0- messagecomponents.consumer : "MessageConsumer"
messagecomponents.injector.email -(0- messagecomponents.service : "MessageService"
messagecomponents.consumer -(0- messagecomponents.service : "MessageService"
@enduml
